// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD86U905RJbvc-JYA0OlMEU1ndEat0TLX4',
    appId: '1:29357367109:web:2bb95be4e1cb7eb723e82c',
    messagingSenderId: '29357367109',
    projectId: 'manga-flutter-d6c4e',
    authDomain: 'manga-flutter-d6c4e.firebaseapp.com',
    storageBucket: 'manga-flutter-d6c4e.firebasestorage.app',
    measurementId: 'G-XEBJPY887D',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCZ7q_TC81Q5jKD9KHLRd6K6E7Q74-JnXA',
    appId: '1:29357367109:android:cb33fe648291c9c323e82c',
    messagingSenderId: '29357367109',
    projectId: 'manga-flutter-d6c4e',
    storageBucket: 'manga-flutter-d6c4e.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCd8M3pmkH_1mr-sQ7WHUIBYKSVp9iVNUg',
    appId: '1:29357367109:ios:4bd5966a17f0e75e23e82c',
    messagingSenderId: '29357367109',
    projectId: 'manga-flutter-d6c4e',
    storageBucket: 'manga-flutter-d6c4e.firebasestorage.app',
    iosBundleId: 'com.example.mangaApp',
  );

}